name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    #runs-on: ubuntu-latest
    runs-on: jiechau/ubuntu
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3 # Updated to v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2 # Updated to v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3 # Updated to v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/jiechau/fluentd:latest
          ghcr.io/jiechau/fluentd:edge
